name: template
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #ui
  cupertino_icons: ^1.0.2
  lottie: ^1.4.3
  cached_network_image: ^3.2.2

  #navigation
  auto_route: ^5.0.2

  #network
  chopper: ^5.1.0
  http: ^0.13.5

  #model mapper
  dart_mappable: ^1.2.0

  #local_storage
  flutter_secure_storage: ^6.0.0

  #state_management
  stacked: ^3.0.0

  #dependeny_injection
  provider: ^6.0.4

  #localization
  easy_localization: ^3.0.1

  #utils
  flutter_svg: ^1.1.5
  file_picker: ^5.2.1
  image_picker: ^0.8.6

  #firebase
  firebase_messaging: ^13.1.0
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2

  #notifications
  flutter_local_notifications: ^12.0.0

  #app_version
  package_info_plus: ^1.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.2
  flutter_gen_runner:
  build_runner: ^2.2.1
  dart_mappable_builder: ^1.2.0
  json_serializable: ^6.5.0
  chopper_generator: ^5.0.1

flutter_gen:
  output: lib/gen
  integrations:
    flutter_svg: true
  assets:
    enabled: true
  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/colors/
    - assets/animations/
    - assets/fonts/

  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 900
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
          weight: 200
